//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ControlsByTopsu.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace AC9649
{
    public partial class @ControlsByTopsu : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @ControlsByTopsu()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlsByTopsu"",
    ""maps"": [
        {
            ""name"": ""Keyboard"",
            ""id"": ""b2d15bb9-cd44-4f69-a796-fab0ddd8d10c"",
            ""actions"": [
                {
                    ""name"": ""CreateSonarPing"",
                    ""type"": ""Button"",
                    ""id"": ""a0f35c1d-7451-499f-a412-5f081050ea18"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""069c348b-5a1f-4dd4-bb6d-020ebc14262a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateSonarPing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Keyboard
            m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
            m_Keyboard_CreateSonarPing = m_Keyboard.FindAction("CreateSonarPing", throwIfNotFound: true);
        }

        ~@ControlsByTopsu()
        {
            UnityEngine.Debug.Assert(!m_Keyboard.enabled, "This will cause a leak and performance issues, ControlsByTopsu.Keyboard.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Keyboard
        private readonly InputActionMap m_Keyboard;
        private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
        private readonly InputAction m_Keyboard_CreateSonarPing;
        public struct KeyboardActions
        {
            private @ControlsByTopsu m_Wrapper;
            public KeyboardActions(@ControlsByTopsu wrapper) { m_Wrapper = wrapper; }
            public InputAction @CreateSonarPing => m_Wrapper.m_Keyboard_CreateSonarPing;
            public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
            public void AddCallbacks(IKeyboardActions instance)
            {
                if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
                @CreateSonarPing.started += instance.OnCreateSonarPing;
                @CreateSonarPing.performed += instance.OnCreateSonarPing;
                @CreateSonarPing.canceled += instance.OnCreateSonarPing;
            }

            private void UnregisterCallbacks(IKeyboardActions instance)
            {
                @CreateSonarPing.started -= instance.OnCreateSonarPing;
                @CreateSonarPing.performed -= instance.OnCreateSonarPing;
                @CreateSonarPing.canceled -= instance.OnCreateSonarPing;
            }

            public void RemoveCallbacks(IKeyboardActions instance)
            {
                if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IKeyboardActions instance)
            {
                foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public KeyboardActions @Keyboard => new KeyboardActions(this);
        public interface IKeyboardActions
        {
            void OnCreateSonarPing(InputAction.CallbackContext context);
        }
    }
}
